<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <RollForward>LatestMajor</RollForward>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.4"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.4"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.4"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.4">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="DotNetEnv" Version="3.1.1"/>
        <PackageReference Include="MessageBox.Avalonia" Version="3.1.5.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0"/>
        <PackageReference Include="ReactiveUI" Version="20.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DatabaseAccess\DatabaseAccess.csproj"/>
        <ProjectReference Include="..\FileServer\FileProcessor\FileProcessor.csproj"/>
        <ProjectReference Include="..\RabbitMQHelper\RabbitMQHelper.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <!-- This ItemGroup is intended to allow the desktop app to build during development while views are being
                    updated to use the new AppStateModel.-->
        <!-- TODO: Remove these as the views are implemented. -->
        <AvaloniaXaml Remove="Views/ConfigView.axaml"/>
        <Compile Remove="Views/ConfigView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/HomeView.axaml"/>
        <Compile Remove="Views/HomeView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/MaintenanceView.axaml"/>
        <Compile Remove="Views/MaintenanceView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/MessagesView.axaml"/>
        <Compile Remove="Views/MessagesView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/PrintersView.axaml"/>
        <Compile Remove="Views/PrintersView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/PrintersView.axaml"/>
        <Compile Remove="Views/PrintersView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/PrintJobsView.axaml"/>
        <Compile Remove="Views/PrintJobsView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/StatsView.axaml"/>
        <Compile Remove="Views/StatsView.axaml.cs"/>
        <AvaloniaXaml Remove="Views/UsersView.axaml"/>
        <Compile Remove="Views/UsersView.axaml.cs"/>
    </ItemGroup>
</Project>
